name: Build Apache Maven Dependency
description: Checkout a repo, build it, and install to the local Apache Maven repository.

branding:
  icon: more-horizontal
  color: purple

inputs:
  repository:
    description: GitHub repository in 'owner/name' form
    required: true
  artifact:
    description: Artifact coordinates 'groupId:artifactId:version[:packaging]' to verify in local Maven repo
    required: false

runs:
  using: composite
  steps:
    - id: tmpdir
      name: Resolve temp workspace
      shell: bash
      run: |
        # Create temporary directory for dependency build
        TMP_DIR="$(mktemp -d)"
        echo "checkout_path=${TMP_DIR}" >> "$GITHUB_OUTPUT"

    - id: checkout-dependency-repo
      name: Checkout dependency repo
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.repository }}
        path: ${{ steps.tmpdir.outputs.checkout_path }}

    - id: build
      name: Build and install dependency
      shell: bash
      working-directory: ${{ steps.tmpdir.outputs.checkout_path }}
      run: |
        # Run Apache Maven build
        pwd
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -DskipTests=true \
          -Dmaven.javadoc.skip=true \
          clean install

    - id: verify-artifact
      name: Verify built artifact (optional)
      shell: bash
      if: ${{ inputs.artifact != '' }}
      run: |
        # Ask Maven to resolve the artifact from the local repository; it fails if the artifact is absent
        mvn \
          --no-transfer-progress \
          --batch-mode \
          --offline \
          -Dmaven.repo.local="$HOME/.m2/repository" \
          -Dartifact="${{ inputs.artifact }}" \
          -Dtransitive=false \
          dependency:get
