name: Build Apache Maven Dependency
description: Checkout a repo, build it, and install to the local Apache Maven repository.

branding:
  icon: more-horizontal
  color: purple

inputs:
  repository:
    description: GitHub repository in 'owner/name' form
    required: true
  artifact:
    description: Artifact coordinates 'groupId:artifactId:version[:packaging]' to verify in local Maven repo
    required: false

runs:
  using: composite
  steps:
    - id: create_checkout_path
      name: Create checkout path
      shell: bash
      run: |
        # Resolve deterministic dependency checkout path; fail if it already exists
        CHECKOUT_PATH="./dependency/${{ inputs.repository }}"
        if [ -e "$CHECKOUT_PATH" ]; then
          echo "Checkout path already exists: $CHECKOUT_PATH" >&2
          exit 1
        fi
        mkdir -p "$(dirname "$CHECKOUT_PATH")"
        mkdir "$CHECKOUT_PATH"
        echo "checkout_path=${CHECKOUT_PATH}" >> "$GITHUB_OUTPUT"
        echo "Using checkout path: ${CHECKOUT_PATH}"

    - id: checkout_dependency_repo
      name: Checkout dependency repo
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.repository }}
        path: ${{ steps.create_checkout_path.outputs.checkout_path }}
        fetch-depth: 1

    - id: build
      name: Build and install dependency
      shell: bash
      working-directory: ${{ steps.create_checkout_path.outputs.checkout_path }}
      run: |
        # Run Apache Maven build
        echo "Using checkout path: `pwd`"
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -DskipTests=true \
          -Dmaven.javadoc.skip=true \
          clean install

    - id: verify_artifact
      name: Verify built artifact (optional)
      shell: bash
      if: ${{ inputs.artifact != '' }}
      run: |
        # Ask Maven to resolve the artifact from the local repository; it fails if the artifact is absent
        mvn \
          --no-transfer-progress \
          --batch-mode \
          --offline \
          -Dmaven.repo.local="$HOME/.m2/repository" \
          -Dartifact="${{ inputs.artifact }}" \
          -Dtransitive=false \
          dependency:get
