name: Build Apache Maven Dependency
description: Checkout a repo, build it, and install to the local Apache Maven repository.

branding:
  icon: more-horizontal
  color: purple

inputs:
  repository:
    description: GitHub repository in 'owner/name' form
    required: true
  artifact:
    description: Artifact coordinates 'groupId:artifactId:version[:packaging]' to verify in local Maven repo
    required: false

runs:
  using: composite
  steps:
    - id: create_checkout_path
      name: Create checkout path
      shell: bash
      run: |
        # Resolve deterministic dependency checkout path; fail if it already exists
        CHECKOUT_PATH="./target/dependency/${{ inputs.repository }}"
        if [ -e "$CHECKOUT_PATH" ]; then
          echo "Checkout path already exists: $CHECKOUT_PATH" >&2
          exit 1
        fi
        mkdir -p "$(dirname "$CHECKOUT_PATH")"
        mkdir "$CHECKOUT_PATH"
        echo "checkout_path=${CHECKOUT_PATH}" >> "$GITHUB_OUTPUT"
        echo "Using checkout path: ${CHECKOUT_PATH}"

    - id: checkout_dependency_repo
      name: Checkout dependency repo
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.repository }}
        path: ${{ steps.create_checkout_path.outputs.checkout_path }}
        fetch-depth: 1

    - id: build
      name: Build and install dependency
      shell: bash
      working-directory: ${{ steps.create_checkout_path.outputs.checkout_path }}
      run: |
        # Run Apache Maven build
        echo "Using checkout path: `pwd`"
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -DskipTests=true \
          -Dmaven.javadoc.skip=true \
          clean install

    - id: verify_artifact
      name: Verify built artifact
      shell: bash
      if: ${{ inputs.artifact != '' }}
      run: |
        # Verify that both JAR and POM exist in the local Maven repository
        GAV="${{ inputs.artifact }}"
        IFS=':' read -r GROUP_ID ARTIFACT_ID VERSION PACKAGING <<< "$GAV"

        if [ -z "$GROUP_ID" ] || [ -z "$ARTIFACT_ID" ] || [ -z "$VERSION" ]; then
          echo "Invalid artifact coordinates: $GAV" >&2
          exit 1
        fi

        : "${PACKAGING:=jar}"

        GROUP_PATH=${GROUP_ID//.//}
        JAR_PATH="$HOME/.m2/repository/$GROUP_PATH/$ARTIFACT_ID/$VERSION/${ARTIFACT_ID}-${VERSION}.${PACKAGING}"
        POM_PATH="$HOME/.m2/repository/$GROUP_PATH/$ARTIFACT_ID/$VERSION/${ARTIFACT_ID}-${VERSION}.pom"

        echo "Resolved artifact coordinates:"
        echo "  groupId: $GROUP_ID"
        echo "  artifactId: $ARTIFACT_ID"
        echo "  version: $VERSION"
        echo "  packaging: $PACKAGING"
        echo "Resolved paths:"
        echo "  JAR: $JAR_PATH"
        echo "  POM: $POM_PATH"

        if [ -f "$JAR_PATH" ] && [ -f "$POM_PATH" ]; then
          echo "✓ GAV $GAV verified:"
          echo "  JAR: $JAR_PATH ($(du -h \"$JAR_PATH\" | cut -f1))"
          echo "  POM: $POM_PATH"
        else
          echo "✗ GAV $GAV missing:"
          echo "  JAR: $([ -f \"$JAR_PATH\" ] || echo 'MISSING')"
          echo "  POM: $([ -f \"$POM_PATH\" ] || echo 'MISSING')"
          exit 1
        fi
